# Generated by Django 5.2.17 on 2026-10-03 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_mode', models.CharField(choices=[('dummy', 'Simulated (dev / testing)'), ('meta', 'Meta WhatsApp Cloud API')], default='dummy', max_length=10)),
                ('whatsapp_phone_number_id', models.CharField(blank=True, max_length=50)),
                ('whatsapp_access_token', models.CharField(blank=True, max_length=255)),
                ('whatsapp_test_mode', models.BooleanField(default=True, help_text='When on, send-test is forced to the test number below.')),
                ('whatsapp_test_number', models.CharField(blank=True, max_length=30)),
                ('default_print_format', models.CharField(choices=[('thermal_80', 'Thermal 80mm receipt'), ('a4', 'A4 invoice')], default='thermal_80', max_length=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='tenants.tenant')),
            ],
        ),
    ]
