# Generated by Django 5.2.17 on 2026-10-03 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_qty', models.DecimalField(decimal_places=3, help_text='Slab activates at this quantity', max_digits=12)),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_slabs', to='catalog.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_slabs', to='tenants.tenant')),
            ],
            options={
                'ordering': ['product__name', 'min_qty'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'product', 'min_qty'), name='uniq_price_slab_per_tenant_product_qty')],
            },
        ),
    ]
