# Generated by Django 5.2.17 on 2026-10-03 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(help_text='Recipient phone number', max_length=30)),
                ('event', models.CharField(help_text='e.g. bill_completed, day_close', max_length=50)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('simulated', 'Simulated (dev)')], default='queued', max_length=20)),
                ('provider_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('bill_completed', 'Bill completed'), ('khata_payment', 'Khata payment received'), ('due_reminder', 'Due / overdue reminder'), ('low_stock', 'Low stock alert'), ('expiry_alert', 'Expiry alert'), ('day_close', 'Day close summary')], max_length=50)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. bill_receipt', max_length=100)),
                ('language', models.CharField(choices=[('en', 'English'), ('ur', 'Urdu')], default='en', max_length=5)),
                ('body', models.TextField(help_text='Use {placeholders}, e.g. {bill_no}, {total}')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
