# Generated by Django 5.2.17 on 2026-10-03 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagelog',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_logs', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='notificationrule',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_rules', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='whatsapptemplate',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Null = global template available to every tenant', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_templates', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.whatsapptemplate'),
        ),
        migrations.AddConstraint(
            model_name='notificationrule',
            constraint=models.UniqueConstraint(fields=('tenant', 'event'), name='uniq_rule_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='whatsapptemplate',
            constraint=models.UniqueConstraint(fields=('tenant', 'name', 'language'), name='uniq_template_per_tenant'),
        ),
    ]
