# Generated by Django 5.2.17 on 2026-10-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapptemplate',
            name='meta_language',
            field=models.CharField(default='en', help_text='Meta template language code, e.g. en, ur.', max_length=10),
        ),
        migrations.AddField(
            model_name='whatsapptemplate',
            name='meta_template_name',
            field=models.CharField(blank=True, help_text='Approved Meta template name, e.g. bill_receipt. When set and the tenant uses the Meta provider, sends go as this template instead of free text.', max_length=100),
        ),
    ]
