# Generated by Django 5.2.17 on 2026-10-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='sale_type',
            field=models.CharField(choices=[('retail', 'Retail'), ('wholesale', 'Wholesale')], default='retail', help_text='Wholesale bills use wholesale rates + volume price slabs', max_length=10),
        ),
        migrations.AddField(
            model_name='billline',
            name='slab_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Volume slab that applied to this line (informational; discount_percent already reflects the winning discount)', max_digits=5),
        ),
    ]
