# Generated by Django 5.2.17 on 2026-10-03 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_bill_sale_type_billline_slab_discount_percent'),
        ('khata', '0003_customer_customer_type_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='applied_promotions',
            field=models.JSONField(default=list, help_text='[{id, name, type, description}] of promotions that fired on this bill'),
        ),
        migrations.AddField(
            model_name='billline',
            name='is_free',
            field=models.BooleanField(default=False, help_text='BOGO free line: rate 0, but stock is still deducted'),
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purpose', models.CharField(choices=[('supplier_payment', 'Supplier payment'), ('expense', 'Shop expense'), ('other', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(help_text='The open shift this payout is deducted from', on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='billing.shift')),
                ('supplier', models.ForeignKey(blank=True, help_text='Set for supplier_payment: also records a khata payment (FIFO)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts', to='khata.supplier')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
