# Generated by Django 5.2.17 on 2026-10-03 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_initial'),
        ('khata', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='khatapayment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='khata_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='khatapayment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='khata_payments', to='khata.customer'),
        ),
        migrations.AddField(
            model_name='khatapayment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='khata_payments', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='billing.bill'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='khata.customer'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='khata.supplier'),
        ),
        migrations.AddField(
            model_name='khatapayment',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='khata_payments', to='khata.supplier'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('tenant', 'phone'), name='uniq_customer_phone_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_supplier_name_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('customer__isnull', False), ('supplier__isnull', True)), models.Q(('customer__isnull', True), ('supplier__isnull', False)), _connector='OR'), name='ledger_exactly_one_party'),
        ),
        migrations.AddConstraint(
            model_name='khatapayment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('customer__isnull', False), ('supplier__isnull', True)), models.Q(('customer__isnull', True), ('supplier__isnull', False)), _connector='OR'), name='khatapayment_exactly_one_party'),
        ),
    ]
