# Generated by Django 5.2.17 on 2026-10-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khata', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('retail', 'Retail'), ('wholesale', 'Wholesale')], default='retail', help_text='Wholesale customers get wholesale rates + volume slabs', max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='wholesale_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Extra automatic bill-level discount for this wholesale customer', max_digits=5),
        ),
    ]
