# Generated by Django 5.2.17 on 2026-10-03 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_priceslab'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('promo_type', models.CharField(choices=[('bogo', 'Buy X get Y free'), ('bundle', 'Bundle discount on two products'), ('percent', 'Bill-level percent off'), ('flat', 'Bill-level flat amount off')], max_length=10)),
                ('buy_qty', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('get_qty', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('min_bill_amount', models.DecimalField(decimal_places=2, default=0, help_text='Bill-level promos only apply when subtotal >= this', max_digits=12)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('days_of_week', models.JSONField(blank=True, default=list, help_text='Weekdays the promo is active, 0=Monday..6=Sunday. Empty = every day.')),
                ('time_start', models.TimeField(blank=True, null=True)),
                ('time_end', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority wins ties between bill-level promos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buy_product', models.ForeignKey(blank=True, help_text='bogo/bundle: the product the customer must buy', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buy_promotions', to='catalog.product')),
                ('get_product', models.ForeignKey(blank=True, help_text='bogo: the free product; bundle: the second discounted product', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_promotions', to='catalog.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-priority', 'name'],
            },
        ),
    ]
